#!/usr/bin/env python3

import sys
import os

# Add the package to Python path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

# Import and run the main function
from gnss_web_dashboard.web_dashboard import main

if __name__ == '__main__':
    main()