<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rover1">

  <!-- Dimensions (Approximate based on 1/10 scale crawler) -->
  <xacro:property name="chassis_length" value="0.3"/>
  <xacro:property name="chassis_width" value="0.2"/>
  <xacro:property name="chassis_height" value="0.1"/>
  <xacro:property name="wheel_radius" value="0.04"/>
  <xacro:property name="wheel_width" value="0.03"/>

  <!-- Base Link (Chassis Center) -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0.0 0.0 0.8 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
  </link>

  <!-- Footprint (Projected on ground) -->
  <link name="base_footprint"/>
  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0 0 -${chassis_height/2 + wheel_radius}" rpy="0 0 0"/>
  </joint>

  <!-- IMU Link -->
  <link name="imu_link">
    <visual>
      <geometry>
        <box size="0.02 0.02 0.01"/>
      </geometry>
      <material name="red">
        <color rgba="1.0 0.0 0.0 1.0"/>
      </material>
    </visual>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 0.05" rpy="0 0 0"/> 
  </joint>

  <!-- GPS Link -->
  <link name="gps_link">
    <visual>
      <geometry>
        <cylinder length="0.02" radius="0.03"/>
      </geometry>
      <material name="black">
        <color rgba="0.1 0.1 0.1 1.0"/>
      </material>
    </visual>
  </link>

  <joint name="gps_joint" type="fixed">
    <parent link="base_link"/>
    <child link="gps_link"/>
    <origin xyz="-0.1 0 0.1" rpy="0 0 0"/>
  </joint>

  <!-- Wheels (Visualization Only) -->
  <xacro:macro name="wheel" params="prefix x y">
    <link name="${prefix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>
    </link>
    <joint name="${prefix}_wheel_joint" type="fixed">
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="${x} ${y} -0.05" rpy="0 0 0"/>
    </joint>
  </xacro:macro>

  <xacro:wheel prefix="front_left" x="0.1" y="0.12"/>
  <xacro:wheel prefix="front_right" x="0.1" y="-0.12"/>
  <xacro:wheel prefix="rear_left" x="-0.1" y="0.12"/>
  <xacro:wheel prefix="rear_right" x="-0.1" y="-0.12"/>

</robot>
