#!/bin/bash
# setup_network.sh
# Configures rover network with WiFi failover using netplan + NetworkManager
# Reads credentials from .env (never committed to git)
#
# This script:
# 1. Generates /etc/netplan/50-rover-network.yaml with WiFi + Ethernet config
# 2. Removes all conflicting netplan configs (the key fix for failover issues)
# 3. Sets NetworkManager priorities for automatic WiFi failover
#
# Usage: sudo ./scripts/setup_network.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$REPO_ROOT/.env"

NETPLAN_FILE="/etc/netplan/50-rover-network.yaml"

# --- Check for root ---
if [[ $EUID -ne 0 ]]; then
    echo "ERROR: This script must be run with sudo"
    echo "Usage: sudo $0"
    exit 1
fi

echo "=== Rover1 Network Setup ==="
echo ""

# --- Check .env exists ---
if [[ ! -f "$ENV_FILE" ]]; then
    echo "ERROR: .env file not found at $ENV_FILE"
    echo ""
    echo "Please create .env with the following variables:"
    echo "  WIFI_HOME_SSID=\"Your Home Network\""
    echo "  WIFI_HOME_PASS=\"your-password\""
    echo "  WIFI_HOTSPOT_SSID=\"Your Phone Hotspot\""
    echo "  WIFI_HOTSPOT_PASS=\"hotspot-password\""
    exit 1
fi

# --- Source .env ---
echo "Loading credentials from .env..."
source "$ENV_FILE"

# --- Validate required variables ---
missing_vars=()
[[ -z "$WIFI_HOME_SSID" ]] && missing_vars+=("WIFI_HOME_SSID")
[[ -z "$WIFI_HOME_PASS" ]] && missing_vars+=("WIFI_HOME_PASS")
[[ -z "$WIFI_HOTSPOT_SSID" ]] && missing_vars+=("WIFI_HOTSPOT_SSID")
[[ -z "$WIFI_HOTSPOT_PASS" ]] && missing_vars+=("WIFI_HOTSPOT_PASS")

if [[ ${#missing_vars[@]} -gt 0 ]]; then
    echo "ERROR: Missing required variables in .env:"
    for var in "${missing_vars[@]}"; do
        echo "  - $var"
    done
    exit 1
fi

echo "  Home WiFi:    $WIFI_HOME_SSID"
echo "  Hotspot:      $WIFI_HOTSPOT_SSID"
echo ""

# --- Remove conflicting netplan configs ---
echo "Removing conflicting netplan configurations..."

# Remove NM-generated configs
for f in /etc/netplan/90-NM-*.yaml; do
    if [[ -f "$f" ]]; then
        echo "  Removing: $f"
        rm -f "$f"
    fi
done

# Remove old rover configs
for f in /etc/netplan/99-rover-network.yaml /etc/netplan/99-tether.yaml; do
    if [[ -f "$f" ]]; then
        echo "  Removing: $f"
        rm -f "$f"
    fi
done

# Handle 50-cloud-init.yaml - remove wifis section if present
CLOUD_INIT="/etc/netplan/50-cloud-init.yaml"
if [[ -f "$CLOUD_INIT" ]]; then
    if grep -q "wifis:" "$CLOUD_INIT" 2>/dev/null; then
        echo "  Stripping WiFi config from: $CLOUD_INIT"
        # Create backup
        cp "$CLOUD_INIT" "${CLOUD_INIT}.bak"
        # Remove wifis section (everything from 'wifis:' to next top-level key or EOF)
        # This uses awk to remove the wifis block
        awk '
            /^wifis:/ { in_wifis=1; next }
            in_wifis && /^[a-z]/ { in_wifis=0 }
            !in_wifis { print }
        ' "${CLOUD_INIT}.bak" > "$CLOUD_INIT"
        echo "  Backup saved: ${CLOUD_INIT}.bak"
    fi
fi

echo ""

# --- Generate netplan config ---
echo "Generating netplan configuration..."

cat > "$NETPLAN_FILE" << EOF
# Rover1 Network Configuration
# Generated by setup_network.sh - DO NOT EDIT MANUALLY
# Re-run the script to regenerate from .env
#
# Priority chain:
#   1. Home WiFi (priority 100) - connects when in range
#   2. Phone Hotspot (priority 50) - fallback when away from home
#   3. Ethernet (10.42.0.1) - always available for tethered SSH
network:
  version: 2
  renderer: NetworkManager

  ethernets:
    eth0:
      dhcp4: true
      optional: true
      addresses:
        - 10.42.0.1/24

  wifis:
    wlan0:
      optional: true
      dhcp4: true
      access-points:
        "${WIFI_HOME_SSID}":
          password: "${WIFI_HOME_PASS}"
        "${WIFI_HOTSPOT_SSID}":
          password: "${WIFI_HOTSPOT_PASS}"
EOF

echo "  Created: $NETPLAN_FILE"

# --- Set secure permissions (contains passwords) ---
chmod 600 "$NETPLAN_FILE"
echo "  Permissions: 600 (root only)"

echo ""

# --- Apply netplan ---
echo "Applying netplan configuration..."
netplan generate
netplan apply
echo "  Netplan applied successfully"

echo ""

# --- Set NetworkManager priorities ---
echo "Configuring NetworkManager connection priorities..."

# Give NetworkManager time to create the connections from netplan
sleep 3

# Set priorities (higher = preferred)
# Home WiFi: priority 100 (try first)
# Hotspot: priority 50 (fallback)
if nmcli connection modify "$WIFI_HOME_SSID" connection.autoconnect-priority 100 2>/dev/null; then
    echo "  $WIFI_HOME_SSID: priority 100 (primary)"
else
    echo "  Warning: Could not set priority for $WIFI_HOME_SSID (connection may not exist yet)"
fi

if nmcli connection modify "$WIFI_HOTSPOT_SSID" connection.autoconnect-priority 50 2>/dev/null; then
    echo "  $WIFI_HOTSPOT_SSID: priority 50 (fallback)"
else
    echo "  Warning: Could not set priority for $WIFI_HOTSPOT_SSID (connection may not exist yet)"
fi

echo ""

# --- Summary ---
echo "=== Network Configuration Complete ==="
echo ""
echo "WiFi Failover Chain:"
echo "  1. $WIFI_HOME_SSID (priority: 100 - primary)"
echo "  2. $WIFI_HOTSPOT_SSID (priority: 50 - fallback)"
echo ""
echo "Ethernet Fallback:"
echo "  Static IP: 10.42.0.1/24 (always available)"
echo "  SSH: ssh andrewmeckley@10.42.0.1"
echo ""
echo "Behavior:"
echo "  - Rover connects to home WiFi when in range"
echo "  - Falls back to phone hotspot when home WiFi unavailable"
echo "  - Ethernet tether always works regardless of WiFi"
echo ""
echo "Verification commands:"
echo "  sudo netplan get              # Show active netplan config"
echo "  nmcli connection show         # List all connections"
echo "  nmcli device status           # Show current connection status"
echo ""
echo "Reboot recommended to verify failover works on boot."
