#!/bin/bash
# setup_wifi_failover.sh — install the 4-tier WiFi failover service.
#
# Idempotent. Safe to re-run. Does:
#   1. Reads .env for WIFI_HOME_*, WIFI_HOTSPOT_*, WIFI_AP_* creds
#   2. Creates / refreshes NetworkManager profiles for Home, Hotspot, AP
#   3. Writes /etc/wifi-failover.conf with the runtime SSIDs
#   4. Installs wifi-failover.sh to /usr/local/bin
#   5. Installs + enables wifi-failover.{service,timer}
#   6. Cleans up the legacy wifi-roam.* units (predecessor 2-tier script)
#
# Usage: sudo ./scripts/setup_wifi_failover.sh

set -e

if [[ $EUID -ne 0 ]]; then
    echo "ERROR: must be run with sudo" >&2
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$REPO_ROOT/.env"

if [ ! -f "$ENV_FILE" ]; then
    echo "ERROR: .env not found at $ENV_FILE — copy .env.example and fill it in" >&2
    exit 1
fi
# shellcheck source=/dev/null
source "$ENV_FILE"

: "${WIFI_HOME_SSID:?WIFI_HOME_SSID missing in .env}"
: "${WIFI_HOME_PASS:?WIFI_HOME_PASS missing in .env}"
: "${WIFI_HOTSPOT_SSID:?WIFI_HOTSPOT_SSID missing in .env}"
: "${WIFI_HOTSPOT_PASS:?WIFI_HOTSPOT_PASS missing in .env}"
: "${WIFI_AP_SSID:?WIFI_AP_SSID missing in .env}"
: "${WIFI_AP_PASS:?WIFI_AP_PASS missing in .env}"

# WPA2 minimum is 8 characters — refuse a too-short password early instead
# of producing a working profile that won't actually authenticate.
if [ ${#WIFI_AP_PASS} -lt 8 ]; then
    echo "ERROR: WIFI_AP_PASS must be at least 8 chars (WPA2 requirement)" >&2
    exit 1
fi

AP_CONN_NAME="rover1-ap"

echo "=== Rover1 WiFi failover setup ==="
echo "  Tier 1 home:    $WIFI_HOME_SSID    (priority 100)"
echo "  Tier 2 hotspot: $WIFI_HOTSPOT_SSID (priority 50)"
echo "  Tier 4 AP:      $WIFI_AP_SSID      (192.168.42.1/24, shared)"
echo

upsert_sta() {
    local conn="$1" ssid="$2" psk="$3" prio="$4"
    if nmcli -t -f NAME connection show | grep -qFx "$conn"; then
        echo "  refreshing existing profile: $conn"
        nmcli connection modify "$conn" \
            802-11-wireless.ssid "$ssid" \
            wifi-sec.key-mgmt wpa-psk \
            wifi-sec.psk "$psk" \
            connection.autoconnect yes \
            connection.autoconnect-priority "$prio"
    else
        echo "  creating profile: $conn"
        nmcli connection add type wifi ifname wlan0 con-name "$conn" \
            ssid "$ssid" \
            wifi-sec.key-mgmt wpa-psk \
            wifi-sec.psk "$psk" \
            connection.autoconnect yes \
            connection.autoconnect-priority "$prio" >/dev/null
    fi
}

echo "Configuring STA profiles..."
upsert_sta "$WIFI_HOME_SSID"    "$WIFI_HOME_SSID"    "$WIFI_HOME_PASS"    100
upsert_sta "$WIFI_HOTSPOT_SSID" "$WIFI_HOTSPOT_SSID" "$WIFI_HOTSPOT_PASS" 50

echo
echo "Configuring AP profile '$AP_CONN_NAME'..."
if nmcli -t -f NAME connection show | grep -qFx "$AP_CONN_NAME"; then
    echo "  refreshing existing AP profile"
    nmcli connection modify "$AP_CONN_NAME" \
        802-11-wireless.ssid "$WIFI_AP_SSID" \
        802-11-wireless.mode ap \
        802-11-wireless.band bg \
        wifi-sec.key-mgmt wpa-psk \
        wifi-sec.psk "$WIFI_AP_PASS" \
        ipv4.method shared \
        ipv4.addresses 192.168.42.1/24 \
        connection.autoconnect no \
        connection.autoconnect-priority 1
else
    echo "  creating AP profile"
    nmcli connection add type wifi ifname wlan0 con-name "$AP_CONN_NAME" \
        ssid "$WIFI_AP_SSID" \
        mode ap \
        802-11-wireless.band bg \
        wifi-sec.key-mgmt wpa-psk \
        wifi-sec.psk "$WIFI_AP_PASS" \
        ipv4.method shared \
        ipv4.addresses 192.168.42.1/24 \
        connection.autoconnect no \
        connection.autoconnect-priority 1 >/dev/null
fi

echo
echo "Writing /etc/wifi-failover.conf..."
cat > /etc/wifi-failover.conf <<EOF
# Generated by setup_wifi_failover.sh — do not edit by hand.
WIFI_HOME_SSID="$WIFI_HOME_SSID"
WIFI_HOTSPOT_SSID="$WIFI_HOTSPOT_SSID"
WIFI_AP_CONN_NAME="$AP_CONN_NAME"
# Seconds to keep AP up before forcing a re-scan for known STAs.
AP_RESCAN_INTERVAL_SEC=300
EOF
chmod 644 /etc/wifi-failover.conf

echo
echo "Installing /usr/local/bin/wifi-failover.sh..."
install -m 755 "$SCRIPT_DIR/wifi-failover.sh" /usr/local/bin/wifi-failover.sh

echo
echo "Cleaning up legacy wifi-roam.* (superseded)..."
for unit in wifi-roam.timer wifi-roam.service; do
    if systemctl is-enabled --quiet "$unit" 2>/dev/null \
       || systemctl is-active --quiet "$unit" 2>/dev/null; then
        systemctl stop "$unit" 2>/dev/null || true
        systemctl disable "$unit" 2>/dev/null || true
        echo "  stopped/disabled: $unit"
    fi
done
rm -f /etc/systemd/system/wifi-roam.service \
      /etc/systemd/system/wifi-roam.timer \
      /usr/local/bin/wifi-roam.sh

echo
echo "Installing systemd units..."
install -m 644 "$REPO_ROOT/systemd/wifi-failover.service" /etc/systemd/system/
install -m 644 "$REPO_ROOT/systemd/wifi-failover.timer"   /etc/systemd/system/

systemctl daemon-reload
systemctl enable --now wifi-failover.timer

echo
echo "=== Done ==="
systemctl status wifi-failover.timer --no-pager | head -8 || true
echo
echo "Manual run:  sudo systemctl start wifi-failover.service"
echo "Tail logs:   journalctl -t wifi-failover -f"
echo
echo "AP details (when active):"
echo "  SSID:     $WIFI_AP_SSID"
echo "  Gateway:  192.168.42.1"
echo "  UI:       http://192.168.42.1:8080"
